apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-project
  labels:
    app: swiggy-project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy-project
  template:
    metadata:
      labels:
        app: swiggy-project
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: swiggy-project
        image: swiggy-project:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
